---
title: "Client Report - What's in a Name"
subtitle: "Course DS 250"
author: "Colton Pritchett"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
import copy
import plotly.graph_objects as go
```


## Elevator pitch

_paste your elevator pitch here_
_A SHORT (4-5 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_type your results and analysis here_

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
colton = df[df['name'] == 'Colton']
chart = px.line(colton, x='year', y='Total', title='Colton over the years')
chart.add_vline(x=2002, annotation_text="My birth")
chart.show()
```

_include figures in chunks and discuss your findings in the figure._

## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_1990_

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here
brittany = df[df['name'] == 'Brittany']
chart = px.line(brittany, x='year', y='Total', title='Brittany over the years')
chart.add_vline(x=1990, annotation_text="My guess")
chart.show()

```

_include figures in chunks and discuss your findings in the figure._


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_type your results and analysis here_

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here
bible_names = copy.deepcopy(df)

bible_names = bible_names[(bible_names['year'] >= 1920) & (bible_names['year'] <= 2000)]

chart = go.Figure()

names_to_plot = ['Mary', 'Martha', 'Peter', 'Paul']

for name in names_to_plot:
    name_data = bible_names[bible_names['name'] == name]
    chart.add_trace(go.Scatter(x=name_data['year'], y=name_data['Total'], mode='lines', name=name))

chart.update_layout(title='Biblical Names from 1920-2000')

chart.show()

```

_include figures in chunks and discuss your findings in the figure._


__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
sabrina = df[df['name'] == 'Sabrina']
chart = px.line(sabrina, x='year', y='Total', title='Sabrina over the years')
chart.add_vline(x=1954, annotation_text="Release of 'Sabrina'")
chart.add_vline(x=1995, annotation_text="Release of 'Sabrina' remake")
chart.show()

```
